[package]
name = "fuzzing_smart_contract"
version = "0.1.0"
edition = "2021"

[dependencies]
web3 = "0.15.0"  # Versão que você pode ajustar conforme necessário
tokio = { version = "1.0", features = ["full"] }

[dev-dependencies]
fuzzcheck = "0.5"
